import "../assets/main.css"
import Link from "next/link"
import Footer from "../components/Footer"
import NavLink from "../components/NavLink"
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <SpeedInsights />
        <div className="bg-gray-200 min-h-[100dvh] grid grid-rows-[auto_1fr_auto] relative">
          <div className="absolute z-0 inset-0 overflow-hidden ">
            <div className="cicle-one blur-2xl w-64 h-64 rounded-full bg-rose-400/50 top-0 right-28 absolute"></div>
            <div className="cicle-two blur-2xl w-64 h-64 rounded-full bg-blue-400/50 bottom-0 left-28 absolute"></div>
          </div>
          <header className="bg-white/50 backdrop-blur">
          <div className="max-w-4xl mx-auto flex items-center justify-between">
              <Link href="/">
            <h2 className="text-2xl text-gray-500 py-6 cursor-pointer">Birch</h2>
          </Link>

            <nav>
              <ul className="flex gap-x-7 text-black-500 text-sm">
                <li>
                  <NavLink text="Home" path="/" />
                </li> 
                <li>
                <NavLink text="The team" path="/our-team" />
                </li> 
                <li>
                <NavLink text="About us" path="/about-us"/>
                </li>     
              </ul>
            </nav>
          </div>
          </header>
        <main className="max-w-4xl mx-auto bg-white/50 rounded-xl py-7 px-8 m-6 overflow-hidden backdrop-blur">{children}</main> 
          <Footer />
        </div>
        </body>        
    </html>
  )
}
